"""Colleague Field has been added

Revision ID: 23c61cf9eb0f
Revises: 865d07bd5d0e
Create Date: 2022-06-03 22:51:48.585743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c61cf9eb0f'
down_revision = '865d07bd5d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleague',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colleague')
    # ### end Alembic commands ###
